function localizeInternalHrefs(html: string, prefix: '' | '/en'): string {
  const root = prefix || '';

  return html
    .replace(
      /href="https:\/\/uvb\.edu\.mx\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/reynosa/$1"`,
    )
    .replace(
      /href='https:\/\/uvb\.edu\.mx\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/reynosa/$1'`,
    )
    .replace(
      /href="https:\/\/uvb\.edu\.mx\/(?!reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/$1"`,
    )
    .replace(
      /href='https:\/\/uvb\.edu\.mx\/(?!reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/$1'`,
    )
    .replace(
      /href="\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/reynosa/$1"`,
    )
    .replace(
      /href='\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/reynosa/$1'`,
    )
    .replace(
      /href="\/(?!en\/|reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/$1"`,
    )
    .replace(
      /href='\/(?!en\/|reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/$1'`,
    );
}

function injectLanguageSwitch(html: string, isEnglish: boolean): string {
  const switchCss = `<style>
.uvb-lang-switch{position:fixed;top:16px;right:20px;z-index:99999;display:flex;gap:8px;align-items:center;padding:6px 10px;border-radius:999px;background:rgba(0,0,0,.35);color:#fff;font-size:12px;letter-spacing:.04em;backdrop-filter:blur(4px)}
.uvb-lang-switch a{color:#fff;text-decoration:none;opacity:.7}
.uvb-lang-switch a.active{opacity:1;font-weight:700}
</style>`;
  const script = `<script>(function(){var p=window.location.pathname||'/';var isEn=${isEnglish ? 'true' : 'false'};var esPath=isEn?p.replace(/^\\/en(?=\\/|$)/,''):p;if(!esPath)esPath='/';var enPath=isEn?p:(p==='/'?'/en/':'/en'+(p.startsWith('/')?p:'/'+p));var box=document.createElement('div');box.className='uvb-lang-switch';box.innerHTML=(isEn?'<a href="'+esPath+'">ES</a><span>|</span><a class="active" href="'+enPath+'">EN</a>':'<a class="active" href="'+esPath+'">ES</a><span>|</span><a href="'+enPath+'">EN</a>');document.body.appendChild(box);})();</script>`;
  return html.replace('</head>', `${switchCss}</head>`).replace('</body>', `${script}</body>`);
}

export function addSpanishLanguageSwitch(html: string): string {
  return injectLanguageSwitch(localizeInternalHrefs(html, ''), false);
}

export function toEnglishLegacyHtml(html: string): string {
  let out = html;

  const replacements: Array<[RegExp, string]> = [
    [/Universidad Valle del Bravo Reynosa/g, 'Valle del Bravo University Reynosa'],
    [/UVB Universidad Valle del Bravo/g, 'UVB Valle del Bravo University'],
    [/Universidad Valle del Bravo/g, 'Valle del Bravo University'],
    [/Somos La Valle, En la Valle Está Mejor/g, 'We Are Valle, Better at Valle'],
    [/Somos La Valle ¡En La Valle Está Mejor!/g, 'We Are Valle! Better at Valle!'],
    [/Reglamento General de Estudiantes de Tipo Superior/g, 'General Regulations for Higher Education Students'],
    [/Reglamento Escolar Bachillerato/g, 'High School Academic Regulations'],
    [/Selecciona tu Campus/g, 'Select your Campus'],
    [/Te damos la bienvenida a la UVB/g, 'Welcome to UVB'],
    [/Normatividad/g, 'Regulations'],
    [/Admisiones/g, 'Admissions'],
    [/Contacto/g, 'Contact'],
    [/Oferta Educativa/g, 'Academic Programs'],
    [/Inicio/g, 'Home'],
    [/Acerca de la UVB/g, 'About UVB'],
    [/Becas/g, 'Scholarships'],
    [/Biblioteca/g, 'Library'],
    [/Licenciaturas/g, 'Undergraduate Programs'],
    [/Preparatoria/g, 'High School'],
    [/Educación Continua/g, 'Continuing Education'],
    [/Conoce nuestros planes de estudio/g, 'Discover our study plans'],
    [/Contamos con un amplio programa de Diplomados/g, 'We offer a broad diploma program'],
    [/Disfruta de una de las etapas más importantes/g, 'Enjoy one of the most important stages'],
    [/Tenemos una oferta académica de siete programas de Licenciatura/g, 'We offer seven undergraduate programs'],
    [/Nuestra Universidad/g, 'Our University'],
    [/Conoce más/g, 'Learn more'],
    [/Campo Laboral/g, 'Career Opportunities'],
    [/MODALIDAD/g, 'FORMAT'],
    [/Modalidad/g, 'Format'],
    [/DURACIÓN/g, 'DURATION'],
    [/Duración/g, 'Duration'],
    [/INICIO DE CURSOS CUATRIMESTRAL/g, 'QUARTER START DATES'],
    [/Inicio de Cursos Cuatrimestral/g, 'Quarter Start Dates'],
    [/Aviso de Privacidad/g, 'Privacy Notice'],
    [/Derechos Reservados/g, 'All Rights Reserved'],
    [/Redes Sociales/g, 'Social Media'],
    [/Reglamento/g, 'Regulations'],
    [/Escuela/g, 'School'],
    [/Contacto y Ubicación/g, 'Contact and Location'],
    [/Plan de Estudios/g, 'Study Plan'],
    [/Perfil de Egreso/g, 'Graduate Profile'],
    [/Perfil de Ingreso/g, 'Admission Profile'],
    [/Objetivo General/g, 'General Objective'],
    [/INTERESES/g, 'INTERESTS'],
    [/HABILIDADES/g, 'SKILLS'],
    [/ACTITUDES/g, 'ATTITUDES'],
    [/Cuatrimestral/g, 'Quarterly'],
    [/Enero \/ Mayo \/ Septiembre/g, 'January / May / September'],
    [/9 ciclos/g, '9 terms'],
    [/8 ciclos/g, '8 terms'],
    [/10 ciclos/g, '10 terms'],
    [/LIC\. EN DERECHO/g, 'B.A. IN LAW'],
    [/LIC\. EN MEDICINA/g, 'M.D. PROGRAM'],
    [/LIC\. EN FISIOTERAPIA/g, 'B.A. IN PHYSICAL THERAPY'],
    [/LIC\. EN CONTADURÍA PÚBLICA Y FINANZAS/g, 'B.A. IN PUBLIC ACCOUNTING AND FINANCE'],
    [/LIC\. EN COMUNICACIÓN Y MEDIOS DIGITALES/g, 'B.A. IN COMMUNICATION AND DIGITAL MEDIA'],
    [/LIC\. EN DISEÑO Y COMUNICACIÓN GRÁFICA/g, 'B.A. IN DESIGN AND GRAPHIC COMMUNICATION'],
    [/LIC\. EN COMERCIO Y LOGÍSTICA INTERNACIONAL/g, 'B.A. IN INTERNATIONAL TRADE AND LOGISTICS'],
    [/LIC\. EN CIRUJANO DENTISTA/g, 'DENTAL SURGERY PROGRAM'],
    [/LIC\. EN ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES/g, 'B.A. IN INTERNATIONAL BUSINESS ADMINISTRATION'],
    [/LIC\. EN INGENIERÍA MECATRÓNICA/g, 'B.A. IN MECHATRONICS ENGINEERING'],
    [/LIC\. EN PSICOLOGÍA/g, 'B.A. IN PSYCHOLOGY'],
    [/IIS &#8211; Ingeniería Industrial y de Sistemas/g, 'IIS &#8211; Industrial and Systems Engineering'],
    [/IMEC &#8211; Licenciatura en Ingeniería Mecatrónica/g, 'IMEC &#8211; B.A. in Mechatronics Engineering'],
    [/LD &#8211; Licenciatura en Derecho/g, 'LD &#8211; B.A. in Law'],
    [/LD &#8211; Licenciatura en Medicina/g, 'LMED &#8211; M.D. Program'],
    [/LF &#8211; Licenciatura en Fisioterapia/g, 'LF &#8211; B.A. in Physical Therapy'],
    [/LCPF &#8211; Licenciatura en Contaduría Pública y Finanzas/g, 'LCPF &#8211; B.A. in Public Accounting and Finance'],
    [/LCMD &#8211; Licenciatura en Comunicación y Medios Digitales/g, 'LCMD &#8211; B.A. in Communication and Digital Media'],
    [/LDCG &#8211; Licenciatura en Diseño y Comunicación Gráfica/g, 'LDCG &#8211; B.A. in Design and Graphic Communication'],
    [/LCLI &#8211; Licenciatura en Comercio y Logística Internacional/g, 'LCLI &#8211; B.A. in International Trade and Logistics'],
    [/LCID &#8211; Licenciatura en Cirujano Dentista/g, 'LCID &#8211; Dental Surgery Program'],
    [/LANI &#8211; Licenciatura en Administración de Negocios Internacionales/g, 'LANI &#8211; B.A. in International Business Administration'],
    [/LPS &#8211; Licenciatura en Psicología/g, 'LPS &#8211; B.A. in Psychology'],
    [/Lic\. en Psicología &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Psychology &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Derecho &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Law &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Ingeniería en Mecatrónica &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Mechatronics Engineering &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Comercio y Logística Internacional &#8211; Valle del Bravo University Reynosa/g, 'B.A. in International Trade and Logistics &#8211; Valle del Bravo University Reynosa'],
    [/High School &#8211; Valle del Bravo University Reynosa/g, 'High School Program &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Psicología/g, 'B.A. in Psychology'],
    [/Lic\. en Derecho/g, 'B.A. in Law'],
    [/Lic\. en Comercio y Logística Internacional/g, 'B.A. in International Trade and Logistics'],
    [/Lic\. en Ingeniería en Mecatrónica/g, 'B.A. in Mechatronics Engineering'],
    [/Lic\. en Fisioterapia &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Physical Therapy &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Medicina &#8211; Valle del Bravo University Reynosa/g, 'M.D. Program &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Cirujano Dentista &#8211; Valle del Bravo University Reynosa/g, 'Dental Surgery Program &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Fisioterapia/g, 'B.A. in Physical Therapy'],
    [/Lic\. en Medicina/g, 'M.D. Program'],
    [/Lic\. en Cirujano Dentista/g, 'Dental Surgery Program'],
    [/Conviértete en un profesional en psicología, aprendiendo a analizar y comprender el comportamiento humano desde múltiples perspectivas\./g, 'Become a psychology professional by learning to analyze and understand human behavior from multiple perspectives.'],
    [/La <strong>Licenciatura en Psicología<\/strong> en la Universidad Valle del Bravo ofrece una formación completa, teórica y práctica, en el estudio de la conducta humana\./g, 'The <strong>B.A. in Psychology</strong> at Valle del Bravo University offers comprehensive theoretical and practical training in the study of human behavior.'],
    [/La <strong>B\.A\. in Psychology<\/strong> en la Valle del Bravo University ofrece una formación completa, teórica y práctica, en el estudio de la conducta humana\./g, 'The <strong>B.A. in Psychology</strong> at Valle del Bravo University offers comprehensive theoretical and practical training in the study of human behavior.'],
    [/La Licenciatura en /g, 'The B.A. in '],
    [/La Ingeniería en /g, 'The Engineering program in '],
    [/ofrece una formación completa, teórica y práctica, en el estudio de la conducta humana\./g, 'offers comprehensive theoretical and practical training in the study of human behavior.'],
    [/Aprenderás a analizar desde aspectos fisioanatómicos hasta ambientales, adquiriendo conocimientos en cómo los factores externos e internos influyen en la interacción de las personas con su entorno y definen su estilo de vida\./g, 'You will learn to analyze everything from physio-anatomical to environmental factors, understanding how internal and external elements shape how people interact with their surroundings and define their lifestyle.'],
    [/Este programa te capacitará en diversas técnicas y habilidades para entender y asistir las necesidades psicológicas de individuos y grupos\./g, 'This program will train you in a wide range of techniques and skills to understand and support the psychological needs of individuals and groups.'],
    [/Desarrollo del pensamiento lógico, matemático, abstracto, analítico y crítico/g, 'Development of logical, mathematical, abstract, analytical, and critical thinking'],
    [/Ética en Psicología/g, 'Ethics in Psychology'],
    [/Instituciones de rehabilitación/g, 'Rehabilitation institutions'],
    [/Hospitales y clínicas/g, 'Hospitals and clinics'],
    [/Centros de educación e investigación/g, 'Education and research centers'],
    [/Consultorio propio/g, 'Private practice'],
    [/Clubes deportivos/g, 'Sports clubs'],
    [/Empresas maquiladoras y gubernamentales/g, 'Manufacturing and government organizations'],
    [/Conocimiento, manejo y comprensión de ciencias/g, 'Knowledge, command, and understanding of the sciences'],
    [/Manejo de sistemas de información/g, 'Use of information systems'],
    [/Manejo de métodos y técnicas de investigación/g, 'Use of research methods and techniques'],
    [/Capacidad de análisis y síntesis/g, 'Analytical and synthesis skills'],
    [/Interés por la lectura y comprensión lectora/g, 'Interest in reading and reading comprehension'],
    [/Interés por la conducta humana/g, 'Interest in human behavior'],
    [/Bases Metodológicas de la Investigación/g, 'Methodological Foundations of Research'],
    [/Métodos Descriptivos en Psicología/g, 'Descriptive Methods in Psychology'],
    [/Epistemología en Psicología/g, 'Epistemology in Psychology'],
    [/Historia de la Psicología/g, 'History of Psychology'],
    [/Teorías Psicológicas de la Personalidad/g, 'Psychological Theories of Personality'],
    [/Entrevista en Psicología/g, 'Interviewing in Psychology'],
    [/Aplicaciones de la Entrevista/g, 'Interview Applications'],
    [/Procesos Psicológicos Básicos/g, 'Basic Psychological Processes'],
    [/Funciones Psicológicas Básicas/g, 'Basic Psychological Functions'],
    [/Funciones Psicológicas Superiores/g, 'Higher Psychological Functions'],
    [/Anatomía y Fisiología del Sistema Nervioso/g, 'Anatomy and Physiology of the Nervous System'],
    [/Bases Neuropsicológicas de la Conducta/g, 'Neuropsychological Foundations of Behavior'],
    [/Aplicaciones Neuropsicológicas al Comportamiento/g, 'Neuropsychological Applications to Behavior'],
    [/Evaluación Neuropsicológica/g, 'Neuropsychological Assessment'],
    [/Psicología del Desarrollo/g, 'Developmental Psychology'],
    [/Psicodesarrollo en la Infancia/g, 'Psychological Development in Childhood'],
    [/Psicodesarrollo en la Adolescencia/g, 'Psychological Development in Adolescence'],
    [/Psicodesarrollo en la Adultez y Senectud/g, 'Psychological Development in Adulthood and Aging'],
    [/Psicología Social/g, 'Social Psychology'],
    [/Psicología de la Personalidad/g, 'Personality Psychology'],
    [/Psicometría/g, 'Psychometrics'],
    [/Psicopatología/g, 'Psychopathology'],
    [/Psicodiagnóstico en la Infancia/g, 'Psychodiagnosis in Childhood'],
    [/Psicodiagnóstico en la Adolescencia/g, 'Psychodiagnosis in Adolescence'],
    [/Psicodiagnóstico en la Adultez y Senectud/g, 'Psychodiagnosis in Adulthood and Aging'],
    [/Psicología Clínica/g, 'Clinical Psychology'],
    [/Psicología Educativa/g, 'Educational Psychology'],
    [/Psicología Organizacional/g, 'Organizational Psychology'],
    [/Prácticas Experimentales en Psicología/g, 'Experimental Practices in Psychology'],
    [/Metodología Cualitativa en Psicología/g, 'Qualitative Methodology in Psychology'],
    [/Técnicas de Modificación Conductual/g, 'Behavior Modification Techniques'],
    [/Pruebas Psicológicas en la Organización/g, 'Psychological Testing in Organizations'],
    [/Modelos de Intervención en Grupos/g, 'Group Intervention Models'],
    [/Pruebas Estadísticas en Psicología/g, 'Statistical Testing in Psychology'],
    [/Psicología Jurídica/g, 'Forensic Psychology'],
    [/Trastornos Psicopatológicos/g, 'Psychopathological Disorders'],
    [/Orientación Educativa y Profesional/g, 'Educational and Career Guidance'],
    [/Diseño e Intervención de Capacitación de Personal/g, 'Design and Training Intervention for Personnel'],
    [/Psicología Comunitaria/g, 'Community Psychology'],
    [/Seminario de Investigación Aplicada/g, 'Applied Research Seminar'],
    [/Psicología Ambiental/g, 'Environmental Psychology'],
    [/Aplicaciones en Psicoterapia/g, 'Applications in Psychotherapy'],
    [/Intervención Psicológica en Educación Especial/g, 'Psychological Intervention in Special Education'],
    [/Desarrollo del Talento Humano/g, 'Human Talent Development'],
    [/Atención Psicosocial a Grupos Vulnerables/g, 'Psychosocial Support for Vulnerable Groups'],
    [/Desarrollo Emprendedor/g, 'Entrepreneurial Development'],
    [/Cultura Internacional del Trabajo/g, 'International Work Culture'],
    [/Intervención Profesional en Salud/g, 'Professional Intervention in Health'],
    [/Intervención Profesional Social/g, 'Professional Social Intervention'],
    [/Seminario de Innovación/g, 'Innovation Seminar'],
    [/Criminología y Victimología/g, 'Criminology and Victimology'],
    [/Taller de Fortalecimiento al Egreso/g, 'Graduation Readiness Workshop'],
    [/Intervención Profesional Organizacional/g, 'Professional Organizational Intervention'],
    [/Intervención Profesional Educativa/g, 'Professional Educational Intervention'],
    [/Intervención en Adicciones y Trastornos de la Alimentación/g, 'Intervention in Addictions and Eating Disorders'],
    [/Seminario de Tendencias Disciplinarias/g, 'Seminar on Disciplinary Trends'],
    [/Intervención en Psicología Familiar/g, 'Intervention in Family Psychology'],
    [/Proceso de Admisión/g, 'Admission Process'],
    [/Nuestra Institución se constituye con base a las necesidades que la sociedad plantea y para ello se establecen objetivos, metas, alternativas y estrategias insertas en un ideal filosófico\./g, 'Our institution is built around the needs raised by society, establishing objectives, goals, alternatives, and strategies grounded in a philosophical ideal.'],
    [/Nuestra institución concibe al individuo libre y solo lo sujetan las leyes naturales, su trabajo consiste en descubrir los supuestos de dichas leyes para tener una concepción científica de la libertad\./g, 'Our institution understands the individual as free, bound only by natural laws; its work is to uncover the principles of those laws in order to develop a scientific understanding of freedom.'],
    [/Nuestra institución busca una formación académica integral en los individuos, apoya la libertad de cátedra con una sola restricción que nos marcan los derechos individuales, por lo cual queda establecido un ambiente de libertad, progreso y trabajo, en donde se desarrollan nuestras actividades\./g, 'Our institution seeks comprehensive academic formation, supports academic freedom with the sole limitation of individual rights, and therefore fosters an environment of freedom, progress, and work where our activities take place.'],
    [/En octubre de 1976, se firma el acta constitutiva de la naciente Valle del Bravo University\. Dando inicio en esta ciudad a tan visionario proyecto en la educación privada\. Las primeras carreras con las que se contaron fueron: Licenciatura en Contaduría Pública y Licenciatura en Administración de Empresas\./g, 'In October 1976, the founding charter of Valle del Bravo University was signed, launching this visionary private education project in the city. The first degree programs offered were Public Accounting and Business Administration.'],
    [/La Universidad Valle de Bravo daba pasos sólidos y firmes como institución educativa y con esta idea básica, la Universidad comienza su crecimiento y expansión con una extraordinaria visión\. Logrando crear ocho campus y dos extensiones educativas en las principales ciudades del Estado de Tamaulipas:/g, 'Valle del Bravo University took firm and steady steps as an educational institution and, with this guiding idea, began its growth and expansion with an extraordinary vision, creating eight campuses and two educational extensions in the main cities of Tamaulipas:'],
    [/La Valle del Bravo University, comienza una nueva etapa, formando parte de la red Universidad Valle de México, trabajando bajo este nombre durante 15 años, viendo surgir muchas generaciones de egresados\./g, 'Valle del Bravo University then entered a new phase as part of the Universidad Valle de México network, operating under that name for 15 years and seeing many generations of graduates emerge.'],
    [/Universidad Valle de México/g, 'Valle de Mexico University'],
    [/Licenciatura en Derecho/g, 'B.A. in Law'],
    [/Introducción al Derecho/g, 'Introduction to Law'],
    [/Derecho Romano/g, 'Roman Law'],
    [/Derecho Penal/g, 'Criminal Law'],
    [/Derecho Constitucional y Control de Convencionalidad/g, 'Constitutional Law and Conventionality Review'],
    [/Bienes y Derechos Reales/g, 'Property and Real Rights'],
    [/Derechos Humanos/g, 'Human Rights'],
    [/Derecho Sucesorio/g, 'Succession Law'],
    [/Derecho de la Administración Pública/g, 'Public Administration Law'],
    [/Derecho Procesal Civil/g, 'Civil Procedure Law'],
    [/Filosofía del Derecho/g, 'Philosophy of Law'],
    [/Derecho Procesal Penal/g, 'Criminal Procedure Law'],
    [/Derecho Fiscal/g, 'Tax Law'],
    [/Derecho Individual del Trabajo/g, 'Individual Labor Law'],
    [/Práctica Forense de Derecho Civil y Familiar/g, 'Forensic Practice in Civil and Family Law'],
    [/Práctica Forense de Derecho Administrativo y Fiscal/g, 'Forensic Practice in Administrative and Tax Law'],
    [/Derecho Colectivo y Práctica Forense de Derecho del Trabajo/g, 'Collective Labor Law and Forensic Labor Law Practice'],
    [/Derecho Procesal Constitucional/g, 'Constitutional Procedural Law'],
    [/Práctica Forense de Derecho de Amparo/g, 'Forensic Constitutional Injunction Practice'],
    [/Preparatoria &#8211; Universidad Valle del Bravo Reynosa/g, 'High School &#8211; Valle del Bravo University Reynosa'],
    [/Ingeniería Industrial y de Sistemas/g, 'Industrial and Systems Engineering'],
    [/Ingeniería Mecatrónica/g, 'Mechatronics Engineering'],
    [/Licenciatura en Ingeniería Mecatrónica/g, 'B.A. in Mechatronics Engineering'],
    [/Licenciatura en Industrial and Systems Engineering/g, 'B.A. in Industrial and Systems Engineering'],
    [/Matemáticas Avanzadas/g, 'Advanced Mathematics'],
    [/Ingeniería Eléctrica/g, 'Electrical Engineering'],
    [/Ingeniería de Servicios/g, 'Service Engineering'],
    [/Ingeniería de Calidad Avanzada/g, 'Advanced Quality Engineering'],
    [/Calidad/g, 'Quality'],
    [/Logística/g, 'Logistics'],
    [/Contabilidad y Finanzas para Ingeniería/g, 'Accounting and Finance for Engineering'],
    [/Gestión de la Calidad/g, 'Quality Management'],
    [/Gestión de la Calidad en los Negocios/g, 'Quality Management in Business'],
    [/Gestión de la Quality/g, 'Quality Management'],
    [/Gestión de la Quality en los Negocios/g, 'Quality Management in Business'],
    [/Estudia en High School UVB y ten Pase Automático a alguna de nuestras Undergraduate Programs o Ingenierías\./g, 'Study at UVB High School and receive automatic admission to one of our undergraduate or engineering programs.'],
    [/Culturales/g, 'Cultural Activities'],
    [/Cultura Digital I/g, 'Digital Culture I'],
    [/Cultura Digital II\*/g, 'Digital Culture II*'],
    [/Taller de Ciencias I/g, 'Science Workshop I'],
    [/Taller de Ciencias II/g, 'Science Workshop II'],
    [/Gestión de Archivos de Texto/g, 'Text File Management'],
    [/Taller de Cultura Digital/g, 'Digital Culture Workshop'],
    [/Temas Selectos de Matemáticas I/g, 'Selected Topics in Mathematics I'],
    [/Contabilidad I/g, 'Accounting I'],
    [/Derecho I/g, 'Law I'],
    [/Temas Selectos de Matemáticas II/g, 'Selected Topics in Mathematics II'],
    [/Contabilidad II/g, 'Accounting II'],
    [/Derecho II/g, 'Law II'],
    [/Prácticas Profesionales/g, 'Professional Internships'],
    [/Inglés General I/g, 'General English I'],
    [/Inglés General II/g, 'General English II'],
    [/Inglés General III/g, 'General English III'],
    [/Inglés General IV/g, 'General English IV'],
    [/Inglés General V/g, 'General English V'],
    [/Estrategias de Aprendizaje y Habilidades Digitales/g, 'Learning Strategies and Digital Skills'],
    [/Pensamiento crítico/g, 'Critical Thinking'],
    [/Probabilidad y Estadística/g, 'Probability and Statistics'],
    [/Matemáticas Aplicadas/g, 'Applied Mathematics'],
    [/Matemáticas Financieras/g, 'Financial Mathematics'],
    [/Contabilidad Financiera/g, 'Financial Accounting'],
    [/Contabilidad Administrativa/g, 'Managerial Accounting'],
    [/Contabilidad de Costos/g, 'Cost Accounting'],
    [/Microeconomía/g, 'Microeconomics'],
    [/Macroeconomía/g, 'Macroeconomics'],
    [/Mercadotecnia/g, 'Marketing'],
    [/Metodología de la Investigación/g, 'Research Methodology'],
    [/Derecho Mercantil/g, 'Commercial Law'],
    [/Derecho Laboral/g, 'Labor Law'],
    [/Comercio Electrónico/g, 'E-Commerce'],
    [/Fotografía Digital/g, 'Digital Photography'],
    [/Manipulación Digital/g, 'Digital Manipulation'],
    [/Programación en Ambiente Web/g, 'Web Environment Programming'],
    [/Control de Calidad/g, 'Quality Control'],
    [/Gestión de la Calidad/g, 'Quality Management'],
    [/Administración Contemporánea/g, 'Contemporary Administration'],
    [/Tecnologías para la Gestión/g, 'Technologies for Management'],
    [/Fundamentos de la Ciencia de Datos/g, 'Foundations of Data Science'],
    [/Narrativa con Datos/g, 'Data Storytelling'],
    [/Diseño y Validación de Instrumentos/g, 'Instrument Design and Validation'],
    [/¡INICIA TU PROCESO DE ADMISIÓN!/g, 'START YOUR ADMISSION PROCESS!'],
    [/Realiza tu proceso de incorporación con ayuda de uno de nuestros asesores\./g, 'Complete your enrollment process with the help of one of our advisors.'],
    [/ADMISIONES/g, 'ADMISSIONS'],
    [/Ubicación/g, 'Location'],
    [/Licenciatura en Administración de Negocios Internacionales/g, 'B.A. in International Business Administration'],
    [/Ética en el actuar/g, 'Ethics in Practice'],
    [/Herramientas para la Gestión Internacional/g, 'Tools for International Management'],
    [/Derecho Aduanero/g, 'Customs Law'],
    [/Logística y [Cc]omercio [Ii]nternacional/g, 'Logistics and International Trade'],
    [/Logistics y [Cc]omercio [Ii]nternacional/g, 'Logistics and International Trade'],
    [/Tratados de [Cc]omercio [Ii]nternacional/g, 'International Trade Treaties'],
    [/Seminario de Negocios Internacionales/g, 'International Business Seminar'],
    [/Licenciatura en Contaduría Pública y Finanzas/g, 'B.A. in Public Accounting and Finance'],
    [/Contabilidad de Activos y Pasivos/g, 'Accounting for Assets and Liabilities'],
    [/Prácticas de Auditoría/g, 'Auditing Practice'],
    [/Licenciatura en Comunicación y Medios Digitales/g, 'B.A. in Communication and Digital Media'],
    [/Taller de Redacción/g, 'Writing Workshop'],
    [/Taller de Creatividad Digital/g, 'Digital Creativity Workshop'],
    [/Cultura y Sociedad Digital/g, 'Digital Culture and Society'],
    [/Licenciatura en Comercio y Logística Internacional/g, 'B.A. in International Trade and Logistics'],
    [/Licenciatura en Comercio y Logistics Internacional/g, 'B.A. in International Trade and Logistics'],
    [/Bases Jurídicas del Comercio Internacional/g, 'Legal Foundations of International Trade'],
    [/Gestión de Negocios Comerciales y Logísticos/g, 'Commercial and Logistics Business Management'],
    [/Auditoría de la Seguridad en la Cadena de Suministro de Comercio Exterior/g, 'Foreign Trade Supply Chain Security Auditing'],
    [/Geoeconomía Aplicada al Comercio Internacional/g, 'Geoeconomics Applied to International Trade'],
    [/Clasificación Arancelaria de Mercancías de Comercio Exterior/g, 'Tariff Classification of Foreign Trade Goods'],
    [/Cultura de Internacionalización de las Empresas/g, 'Business Internationalization Culture'],
    [/Licenciatura en Cirujano Dentista/g, 'Dental Surgery Program'],
    [/Atención humana y profesional al paciente/g, 'Human and Professional Patient Care'],
    [/Seminario de Casos Clínicos/g, 'Clinical Case Seminar'],
    [/Seminario de Fortalecimiento al Egreso/g, 'Graduation Readiness Seminar'],
    [/Licenciatura en Diseño y Comunicación Gráfica/g, 'B.A. in Design and Graphic Communication'],
    [/Desarrollo web y de apps/g, 'Web and App Development'],
    [/Metodología del Diseño y Gestión de Proyectos Creativos/g, 'Design Methodology and Creative Project Management'],
    [/Licenciatura en Fisioterapia/g, 'B.A. in Physical Therapy'],
    [/Desarrollo Humano y Social/g, 'Human and Social Development'],
    [/Introducción a la Fisioterapia/g, 'Introduction to Physical Therapy'],
    [/Desarrollo Psicomotor/g, 'Psychomotor Development'],
    [/Gestión en Salud/g, 'Health Management'],
    [/Fisioterapia Neurológica I/g, 'Neurological Physical Therapy I'],
    [/Fisioterapia Cardiopulmonar/g, 'Cardiopulmonary Physical Therapy'],
    [/Fisioterapia Ortopédica y Traumatológica/g, 'Orthopedic and Traumatological Physical Therapy'],
    [/Fisioterapia Neurológica II/g, 'Neurological Physical Therapy II'],
    [/Fisioterapia Dermato Funcional/g, 'Dermatofunctional Physical Therapy'],
    [/Fisioterapia Urogineco Obstétrica/g, 'Urogynecological and Obstetric Physical Therapy'],
    [/Fisioterapia Comunitaria/g, 'Community Physical Therapy'],
    [/Fisioterapia Reumatológica/g, 'Rheumatological Physical Therapy'],
    [/Fisioterapia en Actividad Física y Deporte/g, 'Physical Therapy in Physical Activity and Sports'],
    [/Fisioterapia Geriátrica/g, 'Geriatric Physical Therapy'],
    [/Seminario Integrador en Fisioterapia I/g, 'Integrative Seminar in Physical Therapy I'],
    [/Estancia de Práctica Profesional Hospitalaria en Fisioterapia/g, 'Hospital Professional Practice Residency in Physical Therapy'],
    [/Estancia de Práctica Profesional en Fisioterapia/g, 'Professional Practice Residency in Physical Therapy'],
    [/Seminario Integrador en Fisioterapia II/g, 'Integrative Seminar in Physical Therapy II'],
    [/Licenciatura en Medicina/g, 'M.D. Program'],
    [/Desarrollo y función del cuerpo humano/g, 'Development and Function of the Human Body'],
    [/Desarrollo del pensamiento lógico-matemático, abstracto, analítico y crítico/g, 'Development of logical-mathematical, abstract, analytical, and critical thinking'],
    [/Agresión y Defensa en Medicina Humana/g, 'Aggression and Defense in Human Medicine'],
    [/Medicina Comunitaria/g, 'Community Medicine'],
    [/Medicina Familiar/g, 'Family Medicine'],
    [/Medicina Legal y Forense/g, 'Legal and Forensic Medicine'],
    [/Medicina Interna/g, 'Internal Medicine'],
    [/Seminario Integrador I/g, 'Integrative Seminar I'],
    [/Seminario Integrador II/g, 'Integrative Seminar II'],
    [/Internado: Medicina Familiar/g, 'Internship: Family Medicine'],
    [/Internado: Medicina Interna/g, 'Internship: Internal Medicine'],
    [/Ética Profesional/g, 'Professional Ethics'],
    [/Licenciatura en Psicología/g, 'B.A. in Psychology'],
    [/Ciclo /g, 'Term '],
  ];

  for (const [pattern, replacement] of replacements) {
    out = out.replace(pattern, replacement);
  }

  out = localizeInternalHrefs(out, '/en');
  out = out.replace(/<html lang="[^"]+"/g, '<html lang="en"');

  return injectLanguageSwitch(out, true);
}
