function localizeInternalHrefs(html: string, prefix: '' | '/en'): string {
  const root = prefix || '';

  return html
    .replace(
      /href="https:\/\/uvb\.edu\.mx\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/reynosa/$1"`,
    )
    .replace(
      /href='https:\/\/uvb\.edu\.mx\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/reynosa/$1'`,
    )
    .replace(
      /href="https:\/\/uvb\.edu\.mx\/(?!reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/$1"`,
    )
    .replace(
      /href='https:\/\/uvb\.edu\.mx\/(?!reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/$1'`,
    )
    .replace(
      /href="\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/reynosa/$1"`,
    )
    .replace(
      /href='\/reynosa\/(?!wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/reynosa/$1'`,
    )
    .replace(
      /href="\/(?!en\/|reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^"]*)"/g,
      `href="${root}/$1"`,
    )
    .replace(
      /href='\/(?!en\/|reynosa\/|wp-content|wp-includes|wp-json|xmlrpc\.php)([^']*)'/g,
      `href='${root}/$1'`,
    );
}

function injectLanguageSwitch(html: string, isEnglish: boolean): string {
  const switchCss = `<style>
.uvb-lang-switch{position:fixed;top:16px;right:20px;z-index:99999;display:flex;gap:8px;align-items:center;padding:6px 10px;border-radius:999px;background:rgba(0,0,0,.35);color:#fff;font-size:12px;letter-spacing:.04em;backdrop-filter:blur(4px)}
.uvb-lang-switch a{color:#fff;text-decoration:none;opacity:.7}
.uvb-lang-switch a.active{opacity:1;font-weight:700}
</style>`;
  const script = `<script>(function(){var p=window.location.pathname||'/';var isEn=${isEnglish ? 'true' : 'false'};var esPath=isEn?p.replace(/^\\/en(?=\\/|$)/,''):p;if(!esPath)esPath='/';var enPath=isEn?p:(p==='/'?'/en/':'/en'+(p.startsWith('/')?p:'/'+p));var box=document.createElement('div');box.className='uvb-lang-switch';box.innerHTML=(isEn?'<a href="'+esPath+'">ES</a><span>|</span><a class="active" href="'+enPath+'">EN</a>':'<a class="active" href="'+esPath+'">ES</a><span>|</span><a href="'+enPath+'">EN</a>');document.body.appendChild(box);})();</script>`;
  return html.replace('</head>', `${switchCss}</head>`).replace('</body>', `${script}</body>`);
}

export function addSpanishLanguageSwitch(html: string): string {
  return injectLanguageSwitch(localizeInternalHrefs(html, ''), false);
}

export function toEnglishLegacyHtml(html: string): string {
  let out = html;

  const replacements: Array<[RegExp, string]> = [
    [/Universidad Valle del Bravo Reynosa/g, 'Valle del Bravo University Reynosa'],
    [/UVB Universidad Valle del Bravo/g, 'UVB Valle del Bravo University'],
    [/Universidad Valle del Bravo/g, 'Valle del Bravo University'],
    [/Somos La Valle, En la Valle Está Mejor/g, 'We Are Valle, Better at Valle'],
    [/Somos La Valle ¡En La Valle Está Mejor!/g, 'We Are Valle! Better at Valle!'],
    [/Reglamento General de Estudiantes de Tipo Superior/g, 'General Regulations for Higher Education Students'],
    [/Reglamento Escolar Bachillerato/g, 'High School Academic Regulations'],
    [/Selecciona tu Campus/g, 'Select your Campus'],
    [/Te damos la bienvenida a la UVB/g, 'Welcome to UVB'],
    [/Normatividad/g, 'Regulations'],
    [/CONTACTO/g, 'CONTACT'],
    [/Teléfonos/g, 'Phone Numbers'],
    [/Conmutador/g, 'Main Line'],
    [/ACERCA DE LA UNIVERSIDAD VALLE DEL BRAVO/g, 'ABOUT VALLE DEL BRAVO UNIVERSITY'],
    [/¡Somos Gente Valle!/g, 'We Are Valle People!'],
    [/BECAS/g, 'SCHOLARSHIPS'],
    [/Apoyamos tu talento y te impulsamos con diferentes becas\. Cumple tus sueños en la UVB\./g, 'We support your talent and help you move forward with different scholarships. Fulfill your dreams at UVB.'],
    [/ADMISSIONS/g, 'ADMISSIONS'],
    [/Acceso a Alumnos/g, 'Student Access'],
    [/ACCESO A ALUMNOS/g, 'STUDENT ACCESS'],
    [/DESCUBRE LA UVB/g, 'DISCOVER UVB'],
    [/Admisiones/g, 'Admissions'],
    [/Contacto/g, 'Contact'],
    [/Oferta Educativa/g, 'Academic Programs'],
    [/Inicio/g, 'Home'],
    [/Acerca de la UVB/g, 'About UVB'],
    [/Becas/g, 'Scholarships'],
    [/Biblioteca/g, 'Library'],
    [/Licenciaturas/g, 'Undergraduate Programs'],
    [/Preparatoria/g, 'High School'],
    [/Educación Continua/g, 'Continuing Education'],
    [/Conoce nuestros planes de estudio/g, 'Discover our study plans'],
    [/Discover our study plans en los que encontrarás tu preparatoria o carrera ideal, que te aportará las herramientas necesarias para una formación académica integral, guiado por un equipo de profesionales de gran experiencia, preparación y calidad humana\./g, 'Discover our study plans and find the high school or degree program that fits you best, supported by the tools you need for a comprehensive academic education guided by experienced, well-prepared professionals.'],
    [/Conoce nuestros planes de estudio en los que encontrarás tu preparatoria o carrera ideal, que te aportará las herramientas necesarias para una formación académica integral, guiado por un equipo de profesionales de gran experiencia, preparación y calidad humana\./g, 'Discover our study plans and find the high school or degree program that fits you best, supported by the tools you need for a comprehensive academic education guided by experienced, well-prepared professionals.'],
    [/Enjoy one of the most important stages en tu vida con preparación integral\./g, 'Enjoy one of the most important stages of your life with comprehensive preparation.'],
    [/Contamos con un amplio programa de Diplomados/g, 'We offer a broad diploma program'],
    [/Disfruta de una de las etapas más importantes/g, 'Enjoy one of the most important stages'],
    [/Tenemos una oferta académica de siete programas de Licenciatura/g, 'We offer seven undergraduate programs'],
    [/Nuestra Universidad/g, 'Our University'],
    [/Nos enfocamos en satisfacer las necesidades sociales con una educación de vanguardia y alta calidad\. Formamos profesionales capaces de comprender y cambiar su entorno, promoviendo la libertad de cátedra como medio para la formación integral\./g, 'We focus on meeting social needs through forward-looking, high-quality education. We train professionals capable of understanding and transforming their environment, promoting academic freedom as a path to comprehensive education.'],
    [/Somos Gente Valle/g, 'We Are Valle People'],
    [/Conoce más/g, 'Learn more'],
    [/Campo Laboral/g, 'Career Opportunities'],
    [/MODALIDAD/g, 'FORMAT'],
    [/Modalidad/g, 'Format'],
    [/DURACIÓN/g, 'DURATION'],
    [/Duración/g, 'Duration'],
    [/INICIO DE CURSOS CUATRIMESTRAL/g, 'QUARTER START DATES'],
    [/Inicio de Cursos Cuatrimestral/g, 'Quarter Start Dates'],
    [/Aviso de Privacidad/g, 'Privacy Notice'],
    [/Derechos Reservados/g, 'All Rights Reserved'],
    [/Redes Sociales/g, 'Social Media'],
    [/Reglamento/g, 'Regulations'],
    [/Escuela/g, 'School'],
    [/Contacto y Ubicación/g, 'Contact and Location'],
    [/Proceso de Admisión/g, 'Admission Process'],
    [/1\. REGISTRO/g, '1. REGISTRATION'],
    [/2\. INFORMACIÓN/g, '2. INFORMATION'],
    [/Hoja de perfilamiento de preparatoria o universidad al llegar a las instalaciones\./g, 'High school or university profile form upon arrival at the facilities.'],
    [/El Departamento de Admissions proporciona la información acerca de preparatoria o universidad\./g, 'The Admissions Department provides information about high school or university programs.'],
    [/El Departamento de Admisiones proporciona la información acerca de preparatoria o universidad\./g, 'The Admissions Department provides information about high school or university programs.'],
    [/Regulations de Scholarships/g, 'Scholarship Regulations'],
    [/Dirígete a nuestra sección de Regulations para poder descargar nuestro reglamento de becas actualizado, en el cual podras conocer toda la información sobre los requisitos para obtener una beca\./g, 'Go to our Regulations section to download the updated scholarship regulations, where you can find all requirements to apply for a scholarship.'],
    [/Ir a Regulations/g, 'Go to Regulations'],
    [/Envíanos un mensaje/g, 'Send Us a Message'],
    [/Nombre\*/g, 'Name*'],
    [/E-Mail\*/g, 'Email*'],
    [/Teléfono \/ WhatsApp\*/g, 'Phone / WhatsApp*'],
    [/Plan de Estudios/g, 'Study Plan'],
    [/Perfil de Egreso/g, 'Graduate Profile'],
    [/Perfil de Ingreso/g, 'Admission Profile'],
    [/Objetivo General/g, 'General Objective'],
    [/INTERESES/g, 'INTERESTS'],
    [/HABILIDADES/g, 'SKILLS'],
    [/ACTITUDES/g, 'ATTITUDES'],
    [/Cuatrimestral/g, 'Quarterly'],
    [/Enero \/ Mayo \/ Septiembre/g, 'January / May / September'],
    [/9 ciclos/g, '9 terms'],
    [/8 ciclos/g, '8 terms'],
    [/10 ciclos/g, '10 terms'],
    [/LIC\. EN DERECHO/g, 'B.A. IN LAW'],
    [/LIC\. EN MEDICINA/g, 'M.D. PROGRAM'],
    [/LIC\. EN FISIOTERAPIA/g, 'B.A. IN PHYSICAL THERAPY'],
    [/LIC\. EN CONTADURÍA PÚBLICA Y FINANZAS/g, 'B.A. IN PUBLIC ACCOUNTING AND FINANCE'],
    [/LIC\. EN COMUNICACIÓN Y MEDIOS DIGITALES/g, 'B.A. IN COMMUNICATION AND DIGITAL MEDIA'],
    [/LIC\. EN DISEÑO Y COMUNICACIÓN GRÁFICA/g, 'B.A. IN DESIGN AND GRAPHIC COMMUNICATION'],
    [/LIC\. EN COMERCIO Y LOGÍSTICA INTERNACIONAL/g, 'B.A. IN INTERNATIONAL TRADE AND LOGISTICS'],
    [/LIC\. EN CIRUJANO DENTISTA/g, 'DENTAL SURGERY PROGRAM'],
    [/LIC\. EN ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES/g, 'B.A. IN INTERNATIONAL BUSINESS ADMINISTRATION'],
    [/LIC\. EN INGENIERÍA MECATRÓNICA/g, 'B.A. IN MECHATRONICS ENGINEERING'],
    [/LIC\. EN PSICOLOGÍA/g, 'B.A. IN PSYCHOLOGY'],
    [/IIS &#8211; Ingeniería Industrial y de Sistemas/g, 'IIS &#8211; Industrial and Systems Engineering'],
    [/IMEC &#8211; Licenciatura en Ingeniería Mecatrónica/g, 'IMEC &#8211; B.A. in Mechatronics Engineering'],
    [/LD &#8211; Licenciatura en Derecho/g, 'LD &#8211; B.A. in Law'],
    [/LD &#8211; Licenciatura en Medicina/g, 'LMED &#8211; M.D. Program'],
    [/LF &#8211; Licenciatura en Fisioterapia/g, 'LF &#8211; B.A. in Physical Therapy'],
    [/LCPF &#8211; Licenciatura en Contaduría Pública y Finanzas/g, 'LCPF &#8211; B.A. in Public Accounting and Finance'],
    [/LCMD &#8211; Licenciatura en Comunicación y Medios Digitales/g, 'LCMD &#8211; B.A. in Communication and Digital Media'],
    [/LDCG &#8211; Licenciatura en Diseño y Comunicación Gráfica/g, 'LDCG &#8211; B.A. in Design and Graphic Communication'],
    [/LCLI &#8211; Licenciatura en Comercio y Logística Internacional/g, 'LCLI &#8211; B.A. in International Trade and Logistics'],
    [/LCID &#8211; Licenciatura en Cirujano Dentista/g, 'LCID &#8211; Dental Surgery Program'],
    [/LANI &#8211; Licenciatura en Administración de Negocios Internacionales/g, 'LANI &#8211; B.A. in International Business Administration'],
    [/LPS &#8211; Licenciatura en Psicología/g, 'LPS &#8211; B.A. in Psychology'],
    [/Lic\. en Psicología &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Psychology &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Derecho &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Law &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Ingeniería en Mecatrónica &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Mechatronics Engineering &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Comercio y Logística Internacional &#8211; Valle del Bravo University Reynosa/g, 'B.A. in International Trade and Logistics &#8211; Valle del Bravo University Reynosa'],
    [/High School &#8211; Valle del Bravo University Reynosa/g, 'High School Program &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Psicología/g, 'B.A. in Psychology'],
    [/Lic\. en Derecho/g, 'B.A. in Law'],
    [/Lic\. en Comercio y Logística Internacional/g, 'B.A. in International Trade and Logistics'],
    [/Lic\. en Ingeniería en Mecatrónica/g, 'B.A. in Mechatronics Engineering'],
    [/Lic\. en Fisioterapia &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Physical Therapy &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Medicina &#8211; Valle del Bravo University Reynosa/g, 'M.D. Program &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Cirujano Dentista &#8211; Valle del Bravo University Reynosa/g, 'Dental Surgery Program &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Fisioterapia/g, 'B.A. in Physical Therapy'],
    [/Lic\. en Medicina/g, 'M.D. Program'],
    [/Lic\. en Cirujano Dentista/g, 'Dental Surgery Program'],
    [/Lic\. en Diseño y Comunicación Gráfica &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Design and Graphic Communication &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Contaduría Pública y Finanzas &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Public Accounting and Finance &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Comunicación y Medios Digitales &#8211; Valle del Bravo University Reynosa/g, 'B.A. in Communication and Digital Media &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Administración de Negocios Internacionales &#8211; Valle del Bravo University Reynosa/g, 'B.A. in International Business Administration &#8211; Valle del Bravo University Reynosa'],
    [/Lic\. en Diseño y Comunicación Gráfica/g, 'B.A. in Design and Graphic Communication'],
    [/Lic\. en Contaduría Pública y Finanzas/g, 'B.A. in Public Accounting and Finance'],
    [/Lic\. en Comunicación y Medios Digitales/g, 'B.A. in Communication and Digital Media'],
    [/Lic\. en Administración de Negocios Internacionales/g, 'B.A. in International Business Administration'],
    [/Conviértete en un profesional en psicología, aprendiendo a analizar y comprender el comportamiento humano desde múltiples perspectivas\./g, 'Become a psychology professional by learning to analyze and understand human behavior from multiple perspectives.'],
    [/Sé parte de la revolución digital en comunicación, creando contenidos innovadores para medios electrónicos y tradicionales\./g, 'Be part of the digital communication revolution, creating innovative content for electronic and traditional media.'],
    [/Conviértete en un fisioterapeuta altamente capacitado, combinando ciencia, técnica y vocación para mejorar la movilidad y calidad de vida de los demás\./g, 'Become a highly skilled physical therapist, combining science, technique, and vocation to improve the mobility and quality of life of others.'],
    [/Transforma tu pasión por el diseño en una carrera profesional, aprendiendo a comunicar ideas a través de medios gráficos y digitales\./g, 'Turn your passion for design into a professional career, learning to communicate ideas through graphic and digital media.'],
    [/Desarrolla tus habilidades en una de las ramas más importantes de la salud, con formación teórica y práctica en diagnóstico y tratamiento dental\./g, 'Develop your skills in one of the most important fields of health, with theoretical and practical training in dental diagnosis and treatment.'],
    [/Conviértete en un médico altamente capacitado, combinando conocimientos teóricos y prácticos para mejorar la salud de los demás\./g, 'Become a highly skilled physician, combining theoretical and practical knowledge to improve the health of others.'],
    [/Domina las habilidades necesarias para identificar oportunidades de negocio y gestionar operaciones internacionales con éxito\./g, 'Master the skills needed to identify business opportunities and manage international operations successfully.'],
    [/Conviértete en un experto en contaduría y finanzas, dominando las técnicas de análisis financiero y control de operaciones empresariales\./g, 'Become an expert in accounting and finance, mastering financial analysis techniques and business operations control.'],
    [/La <strong>Licenciatura en Psicología<\/strong> en la Universidad Valle del Bravo ofrece una formación completa, teórica y práctica, en el estudio de la conducta humana\./g, 'The <strong>B.A. in Psychology</strong> at Valle del Bravo University offers comprehensive theoretical and practical training in the study of human behavior.'],
    [/La <strong>B\.A\. in Psychology<\/strong> en la Valle del Bravo University ofrece una formación completa, teórica y práctica, en el estudio de la conducta humana\./g, 'The <strong>B.A. in Psychology</strong> at Valle del Bravo University offers comprehensive theoretical and practical training in the study of human behavior.'],
    [/La Licenciatura en /g, 'The B.A. in '],
    [/La Ingeniería en /g, 'The Engineering program in '],
    [/en la UVB es para aquellos interesados en liderar la transformación digital en comunicación\./g, 'at UVB is designed for students interested in leading the digital transformation of communication.'],
    [/Este programa te capacita en la elaboración de contenidos y mensajes para canales electrónicos y tradicionales, usando herramientas avanzadas\./g, 'This program trains you to create content and messages for electronic and traditional channels using advanced tools.'],
    [/Ideal para trabajar en medios, comunicación organizacional, publicidad, marketing o política, la carrera de LCMD desarrolla habilidades en producción audiovisual, estrategia digital y análisis de medios\./g, 'Ideal for work in media, organizational communication, advertising, marketing, or politics, the LCMD program develops skills in audiovisual production, digital strategy, and media analysis.'],
    [/Si te apasiona la comunicación en todas sus formas, esta licenciatura te abrirá puertas a un mundo de oportunidades\./g, 'If you are passionate about communication in all its forms, this degree will open the door to a world of opportunities.'],
    [/en la Valle del Bravo University es ideal para quienes tienen interés en el cuerpo humano, el movimiento y la recuperación funcional de las personas\./g, 'at Valle del Bravo University is ideal for those interested in the human body, movement, and people\'s functional recovery.'],
    [/Si te motiva ayudar a otros a mejorar su calidad de vida a través de la rehabilitación física y cuentas con vocación de servicio, sensibilidad humana y compromiso, esta carrera es para ti\./g, 'If you are motivated to help others improve their quality of life through physical rehabilitation and you have a vocation for service, empathy, and commitment, this program is for you.'],
    [/Te ofrece una formación integral en fisioterapia, basada en la evidencia y orientada a la prevención, tratamiento y recuperación del bienestar físico\./g, 'It offers comprehensive training in physical therapy, grounded in evidence and focused on prevention, treatment, and recovery of physical well-being.'],
    [/En la UVB contamos con todo lo necesario para tu desarrollo profesional: laboratorios, salas de prácticas, áreas de evaluación y rehabilitación física, consultorios equipados y espacios diseñados para el aprendizaje práctico\./g, 'At UVB, we provide everything needed for your professional development: laboratories, practice rooms, physical assessment and rehabilitation areas, fully equipped clinics, and spaces designed for hands-on learning.'],
    [/en la Valle del Bravo University es ideal si te apasiona la fusión de diseño, comunicación y tecnología digital\./g, 'at Valle del Bravo University is ideal if you are passionate about the fusion of design, communication, and digital technology.'],
    [/Este programa te permite desarrollar tu creatividad, creando mensajes visuales impactantes mediante tecnologías de vanguardia\./g, 'This program allows you to develop your creativity by creating powerful visual messages through cutting-edge technologies.'],
    [/Aprenderás a participar en campañas de branding, promoción de productos y a dominar las tecnologías digitales más recientes para proyectos de diseño innovadores y comunicación efectiva\./g, 'You will learn to contribute to branding campaigns, product promotion, and master the latest digital technologies for innovative design projects and effective communication.'],
    [/Es perfecta para aquellos que buscan dejar huella en el mundo del diseño digital\./g, 'It is perfect for those who want to leave a mark in the world of digital design.'],
    [/Si te interesa una de las ramas más importantes de la salud, la/g, 'If you are interested in one of the most important branches of health, the '],
    [/de la Valle del Bravo University es la opción ideal\./g, 'at Valle del Bravo University is the ideal option.'],
    [/Aprenderás de forma teórica y práctica los conocimientos necesarios para diagnosticar y tratar pacientes en el área bucal, cabeza y cuello\./g, 'You will learn, both theoretically and practically, the knowledge needed to diagnose and treat patients in the oral, head, and neck areas.'],
    [/En la UVB contamos con todos los equipos necesarios para tu formación, incluyendo laboratorios, consultorios y el instrumental adecuado\./g, 'At UVB, we have all the equipment necessary for your training, including laboratories, clinics, and proper instruments.'],
    [/Este programa te preparará para desempeñarte profesionalmente en el cuidado dental, abarcando desde la prevención hasta tratamientos avanzados, asegurando la salud y bienestar de tus pacientes\./g, 'This program will prepare you to work professionally in dental care, covering everything from prevention to advanced treatments and ensuring the health and well-being of your patients.'],
    [/en la Valle del Bravo University es ideal para aquellos con pasión por las ciencias y un profundo interés en el cuerpo humano y su funcionamiento\./g, 'at Valle del Bravo University is ideal for those with a passion for science and a deep interest in the human body and how it works.'],
    [/Si posees un fuerte sentido humanístico y de responsabilidad, y tu objetivo es mejorar la salud física, mental y psicosocial de las personas, esta carrera es para ti\./g, 'If you have a strong humanistic sense and a deep sense of responsibility, and your goal is to improve the physical, mental, and psychosocial health of people, this program is for you.'],
    [/Te ofrece una educación integral en medicina, enfocada en la investigación para contribuir a avances significativos en la salud de la población\./g, 'It offers a comprehensive education in medicine, focused on research to contribute to significant advances in public health.'],
    [/En la UVB contamos con todo el equipo e instalaciones necesarias para el desarrollo de la carrera: laboratorios, aulas, simuladores de quirófanos y consultorios, salas de prácticas y mucho más\./g, 'At UVB, we provide all the equipment and facilities required for the program: laboratories, classrooms, operating room simulators, clinics, practice rooms, and much more.'],
    [/en la UVB forma profesionales expertos en la gestión global de empresas\./g, 'at UVB trains professionals who are experts in global business management.'],
    [/Combina conocimientos en economía, finanzas, marketing y comercio internacional para desarrollar estrategias efectivas en un mercado globalizado\./g, 'It combines knowledge of economics, finance, marketing, and international trade to develop effective strategies in a globalized market.'],
    [/Aprenderás a identificar oportunidades de negocio, gestionar operaciones internacionales y aplicar técnicas de negociación intercultural\./g, 'You will learn to identify business opportunities, manage international operations, and apply intercultural negotiation techniques.'],
    [/Este programa te preparará para enfrentar los retos del comercio global y liderar empresas en mercados internacionales, impulsando su crecimiento y éxito\./g, 'This program will prepare you to face the challenges of global trade and lead companies in international markets, driving growth and success.'],
    [/en la UVB es un programa diseñado para formar profesionales con una sólida base en conocimientos teóricos y prácticos esenciales en el mundo del comercio global\./g, 'at UVB is a program designed to prepare professionals with a strong foundation in essential theoretical and practical knowledge for the world of global trade.'],
    [/Esta carrera te preparará para analizar e interpretar las dinámicas de los nuevos mercados internacionales, manejar eficientemente las divisas y comprender los aspectos arancelarios críticos\./g, 'This degree will prepare you to analyze and interpret the dynamics of new international markets, manage currencies efficiently, and understand critical tariff issues.'],
    [/Además, adquirirás habilidades clave para identificar oportunidades de inversión extranjera y desarrollar estrategias de comercio efectivas\./g, 'In addition, you will acquire key skills to identify foreign investment opportunities and develop effective trade strategies.'],
    [/El programa también se enfoca en la logística internacional, enseñándote a optimizar cadenas de suministro y manejar operaciones de comercio exterior\./g, 'The program also focuses on international logistics, teaching you to optimize supply chains and manage foreign trade operations.'],
    [/de la UVB es la elección perfecta si tu meta es destacar en el sector fiscal y financiero\./g, 'at UVB is the perfect choice if your goal is to stand out in the tax and financial sector.'],
    [/Este programa está diseñado para aquellos que desean aprender a implementar sistemas y técnicas contables avanzadas para el control eficiente de operaciones y resultados empresariales\./g, 'This program is designed for those who want to learn how to implement advanced accounting systems and techniques for the efficient control of business operations and results.'],
    [/Además, te brindará los conocimientos necesarios para generar información financiera clave para la salud organizacional\./g, 'It will also provide you with the knowledge necessary to generate financial information that is essential to organizational health.'],
    [/Si te gusta la idea de poseer las herramientas para analizar y evaluar mercados financieros, esta carrera te preparará para ello, desarrollando tus habilidades en análisis financiero, auditoría y estrategia fiscal\./g, 'If you like the idea of having the tools to analyze and evaluate financial markets, this degree will prepare you for it by developing your skills in financial analysis, auditing, and tax strategy.'],
    [/ofrece una formación completa, teórica y práctica, en el estudio de la conducta humana\./g, 'offers comprehensive theoretical and practical training in the study of human behavior.'],
    [/Aprenderás a analizar desde aspectos fisioanatómicos hasta ambientales, adquiriendo conocimientos en cómo los factores externos e internos influyen en la interacción de las personas con su entorno y definen su estilo de vida\./g, 'You will learn to analyze everything from physio-anatomical to environmental factors, understanding how internal and external elements shape how people interact with their surroundings and define their lifestyle.'],
    [/Este programa te capacitará en diversas técnicas y habilidades para entender y asistir las necesidades psicológicas de individuos y grupos\./g, 'This program will train you in a wide range of techniques and skills to understand and support the psychological needs of individuals and groups.'],
    [/Desarrollo del pensamiento lógico, matemático, abstracto, analítico y crítico/g, 'Development of logical, mathematical, abstract, analytical, and critical thinking'],
    [/Ética en Psicología/g, 'Ethics in Psychology'],
    [/Instituciones de rehabilitación/g, 'Rehabilitation institutions'],
    [/Hospitales y clínicas/g, 'Hospitals and clinics'],
    [/Centros de educación e investigación/g, 'Education and research centers'],
    [/Consultorio propio/g, 'Private practice'],
    [/Clubes deportivos/g, 'Sports clubs'],
    [/Empresas maquiladoras y gubernamentales/g, 'Manufacturing and government organizations'],
    [/Agencias de medios digitales/g, 'Digital media agencies'],
    [/Áreas de comunicación social de dependencias gubernamentales/g, 'Social communication departments within government agencies'],
    [/Medios de comunicación tradicionales y digitales/g, 'Traditional and digital media outlets'],
    [/Áreas de comunicación en empresas y corporaciones/g, 'Communication departments in companies and corporations'],
    [/Agencias de publicidad, mercadotecnia o relaciones públicas/g, 'Advertising, marketing, or public relations agencies'],
    [/Tu propia agencia de comunicación y relaciones públicas/g, 'Your own communication and public relations agency'],
    [/Clínicas y hospitales públicos o privados/g, 'Public or private clinics and hospitals'],
    [/Consultorios y centros de rehabilitación física/g, 'Clinics and physical rehabilitation centers'],
    [/centros de atención a personas con discapacidad/g, 'care centers for people with disabilities'],
    [/Práctica privada y emprendimiento en fisioterapia/g, 'Private practice and entrepreneurship in physical therapy'],
    [/Investigación en ciencias de la salud y terapia física/g, 'Research in health sciences and physical therapy'],
    [/Empresas productoras de medios/g, 'Media production companies'],
    [/Despachos de diseño/g, 'Design studios'],
    [/Casas de animación o productoras/g, 'Animation studios or production houses'],
    [/Instituciones médicas públicas/g, 'Public medical institutions'],
    [/Consultorios médicos dentales privados/g, 'Private dental clinics'],
    [/Clínicas y hospitales públicos y privados/g, 'Public and private clinics and hospitals'],
    [/Área industrial y laboral/g, 'Industrial and labor sector'],
    [/Docencia e investigación/g, 'Teaching and research'],
    [/Área administrativa de instituciones de salud públicas y privadas/g, 'Administrative departments of public and private health institutions'],
    [/Empresas de importación y exportación de productos/g, 'Import and export companies'],
    [/Consultoría de proyectos internacionales/g, 'International project consulting'],
    [/Consultoría independiente/g, 'Independent consulting'],
    [/Empresas y organismos públicos y privados/g, 'Public and private companies and organizations'],
    [/Conocimiento, manejo y comprensión de ciencias/g, 'Knowledge, command, and understanding of the sciences'],
    [/Manejo de sistemas de información/g, 'Use of information systems'],
    [/Manejo de métodos y técnicas de investigación/g, 'Use of research methods and techniques'],
    [/Capacidad de análisis y síntesis/g, 'Analytical and synthesis skills'],
    [/Interés por la lectura y comprensión lectora/g, 'Interest in reading and reading comprehension'],
    [/Interés por la conducta humana/g, 'Interest in human behavior'],
    [/Bases Metodológicas de la Investigación/g, 'Methodological Foundations of Research'],
    [/Métodos Descriptivos en Psicología/g, 'Descriptive Methods in Psychology'],
    [/Epistemología en Psicología/g, 'Epistemology in Psychology'],
    [/Historia de la Psicología/g, 'History of Psychology'],
    [/Teorías Psicológicas de la Personalidad/g, 'Psychological Theories of Personality'],
    [/Entrevista en Psicología/g, 'Interviewing in Psychology'],
    [/Aplicaciones de la Entrevista/g, 'Interview Applications'],
    [/Procesos Psicológicos Básicos/g, 'Basic Psychological Processes'],
    [/Funciones Psicológicas Básicas/g, 'Basic Psychological Functions'],
    [/Funciones Psicológicas Superiores/g, 'Higher Psychological Functions'],
    [/Anatomía y Fisiología del Sistema Nervioso/g, 'Anatomy and Physiology of the Nervous System'],
    [/Bases Neuropsicológicas de la Conducta/g, 'Neuropsychological Foundations of Behavior'],
    [/Aplicaciones Neuropsicológicas al Comportamiento/g, 'Neuropsychological Applications to Behavior'],
    [/Evaluación Neuropsicológica/g, 'Neuropsychological Assessment'],
    [/Psicología del Desarrollo/g, 'Developmental Psychology'],
    [/Psicodesarrollo en la Infancia/g, 'Psychological Development in Childhood'],
    [/Psicodesarrollo en la Adolescencia/g, 'Psychological Development in Adolescence'],
    [/Psicodesarrollo en la Adultez y Senectud/g, 'Psychological Development in Adulthood and Aging'],
    [/Psicología Social/g, 'Social Psychology'],
    [/Psicología de la Personalidad/g, 'Personality Psychology'],
    [/Psicometría/g, 'Psychometrics'],
    [/Psicopatología/g, 'Psychopathology'],
    [/Psicodiagnóstico en la Infancia/g, 'Psychodiagnosis in Childhood'],
    [/Psicodiagnóstico en la Adolescencia/g, 'Psychodiagnosis in Adolescence'],
    [/Psicodiagnóstico en la Adultez y Senectud/g, 'Psychodiagnosis in Adulthood and Aging'],
    [/Psicología Clínica/g, 'Clinical Psychology'],
    [/Psicología Educativa/g, 'Educational Psychology'],
    [/Psicología Organizacional/g, 'Organizational Psychology'],
    [/Prácticas Experimentales en Psicología/g, 'Experimental Practices in Psychology'],
    [/Metodología Cualitativa en Psicología/g, 'Qualitative Methodology in Psychology'],
    [/Técnicas de Modificación Conductual/g, 'Behavior Modification Techniques'],
    [/Pruebas Psicológicas en la Organización/g, 'Psychological Testing in Organizations'],
    [/Modelos de Intervención en Grupos/g, 'Group Intervention Models'],
    [/Pruebas Estadísticas en Psicología/g, 'Statistical Testing in Psychology'],
    [/Psicología Jurídica/g, 'Forensic Psychology'],
    [/Trastornos Psicopatológicos/g, 'Psychopathological Disorders'],
    [/Orientación Educativa y Profesional/g, 'Educational and Career Guidance'],
    [/Diseño e Intervención de Capacitación de Personal/g, 'Design and Training Intervention for Personnel'],
    [/Psicología Comunitaria/g, 'Community Psychology'],
    [/Seminario de Investigación Aplicada/g, 'Applied Research Seminar'],
    [/Psicología Ambiental/g, 'Environmental Psychology'],
    [/Aplicaciones en Psicoterapia/g, 'Applications in Psychotherapy'],
    [/Intervención Psicológica en Educación Especial/g, 'Psychological Intervention in Special Education'],
    [/Desarrollo del Talento Humano/g, 'Human Talent Development'],
    [/Atención Psicosocial a Grupos Vulnerables/g, 'Psychosocial Support for Vulnerable Groups'],
    [/Desarrollo Emprendedor/g, 'Entrepreneurial Development'],
    [/Cultura Internacional del Trabajo/g, 'International Work Culture'],
    [/Intervención Profesional en Salud/g, 'Professional Intervention in Health'],
    [/Intervención Profesional Social/g, 'Professional Social Intervention'],
    [/Seminario de Innovación/g, 'Innovation Seminar'],
    [/Criminología y Victimología/g, 'Criminology and Victimology'],
    [/Taller de Fortalecimiento al Egreso/g, 'Graduation Readiness Workshop'],
    [/Intervención Profesional Organizacional/g, 'Professional Organizational Intervention'],
    [/Intervención Profesional Educativa/g, 'Professional Educational Intervention'],
    [/Intervención en Adicciones y Trastornos de la Alimentación/g, 'Intervention in Addictions and Eating Disorders'],
    [/Seminario de Tendencias Disciplinarias/g, 'Seminar on Disciplinary Trends'],
    [/Intervención en Psicología Familiar/g, 'Intervention in Family Psychology'],
    [/Proceso de Admisión/g, 'Admission Process'],
    [/Nuestra Institución se constituye con base a las necesidades que la sociedad plantea y para ello se establecen objetivos, metas, alternativas y estrategias insertas en un ideal filosófico\./g, 'Our institution is built around the needs raised by society, establishing objectives, goals, alternatives, and strategies grounded in a philosophical ideal.'],
    [/Nuestra institución concibe al individuo libre y solo lo sujetan las leyes naturales, su trabajo consiste en descubrir los supuestos de dichas leyes para tener una concepción científica de la libertad\./g, 'Our institution understands the individual as free, bound only by natural laws; its work is to uncover the principles of those laws in order to develop a scientific understanding of freedom.'],
    [/Nuestra institución busca una formación académica integral en los individuos, apoya la libertad de cátedra con una sola restricción que nos marcan los derechos individuales, por lo cual queda establecido un ambiente de libertad, progreso y trabajo, en donde se desarrollan nuestras actividades\./g, 'Our institution seeks comprehensive academic formation, supports academic freedom with the sole limitation of individual rights, and therefore fosters an environment of freedom, progress, and work where our activities take place.'],
    [/En octubre de 1976, se firma el acta constitutiva de la naciente Valle del Bravo University\. Dando inicio en esta ciudad a tan visionario proyecto en la educación privada\. Las primeras carreras con las que se contaron fueron: Licenciatura en Contaduría Pública y Licenciatura en Administración de Empresas\./g, 'In October 1976, the founding charter of Valle del Bravo University was signed, launching this visionary private education project in the city. The first degree programs offered were Public Accounting and Business Administration.'],
    [/La Universidad Valle de Bravo daba pasos sólidos y firmes como institución educativa y con esta idea básica, la Universidad comienza su crecimiento y expansión con una extraordinaria visión\. Logrando crear ocho campus y dos extensiones educativas en las principales ciudades del Estado de Tamaulipas:/g, 'Valle del Bravo University took firm and steady steps as an educational institution and, with this guiding idea, began its growth and expansion with an extraordinary vision, creating eight campuses and two educational extensions in the main cities of Tamaulipas:'],
    [/La Valle del Bravo University, comienza una nueva etapa, formando parte de la red Universidad Valle de México, trabajando bajo este nombre durante 15 años, viendo surgir muchas generaciones de egresados\./g, 'Valle del Bravo University then entered a new phase as part of the Universidad Valle de México network, operating under that name for 15 years and seeing many generations of graduates emerge.'],
    [/Universidad Valle de México/g, 'Valle de Mexico University'],
    [/Licenciatura en Derecho/g, 'B.A. in Law'],
    [/Introducción al Derecho/g, 'Introduction to Law'],
    [/Derecho Romano/g, 'Roman Law'],
    [/Derecho Penal/g, 'Criminal Law'],
    [/Derecho Constitucional y Control de Convencionalidad/g, 'Constitutional Law and Conventionality Review'],
    [/Bienes y Derechos Reales/g, 'Property and Real Rights'],
    [/Derechos Humanos/g, 'Human Rights'],
    [/Derecho Sucesorio/g, 'Succession Law'],
    [/Derecho de la Administración Pública/g, 'Public Administration Law'],
    [/Derecho Procesal Civil/g, 'Civil Procedure Law'],
    [/Filosofía del Derecho/g, 'Philosophy of Law'],
    [/Derecho Procesal Penal/g, 'Criminal Procedure Law'],
    [/Derecho Fiscal/g, 'Tax Law'],
    [/Derecho Individual del Trabajo/g, 'Individual Labor Law'],
    [/Práctica Forense de Derecho Civil y Familiar/g, 'Forensic Practice in Civil and Family Law'],
    [/Práctica Forense de Derecho Administrativo y Fiscal/g, 'Forensic Practice in Administrative and Tax Law'],
    [/Derecho Colectivo y Práctica Forense de Derecho del Trabajo/g, 'Collective Labor Law and Forensic Labor Law Practice'],
    [/Derecho Procesal Constitucional/g, 'Constitutional Procedural Law'],
    [/Práctica Forense de Derecho de Amparo/g, 'Forensic Constitutional Injunction Practice'],
    [/Preparatoria &#8211; Universidad Valle del Bravo Reynosa/g, 'High School &#8211; Valle del Bravo University Reynosa'],
    [/Ingeniería Industrial y de Sistemas/g, 'Industrial and Systems Engineering'],
    [/Ingeniería Mecatrónica/g, 'Mechatronics Engineering'],
    [/Licenciatura en Ingeniería Mecatrónica/g, 'B.A. in Mechatronics Engineering'],
    [/Licenciatura en Industrial and Systems Engineering/g, 'B.A. in Industrial and Systems Engineering'],
    [/Matemáticas Avanzadas/g, 'Advanced Mathematics'],
    [/Ingeniería Eléctrica/g, 'Electrical Engineering'],
    [/Ingeniería de Servicios/g, 'Service Engineering'],
    [/Ingeniería de Calidad Avanzada/g, 'Advanced Quality Engineering'],
    [/Calidad/g, 'Quality'],
    [/Logística/g, 'Logistics'],
    [/Contabilidad y Finanzas para Ingeniería/g, 'Accounting and Finance for Engineering'],
    [/Gestión de la Calidad/g, 'Quality Management'],
    [/Gestión de la Calidad en los Negocios/g, 'Quality Management in Business'],
    [/Gestión de la Quality/g, 'Quality Management'],
    [/Gestión de la Quality en los Negocios/g, 'Quality Management in Business'],
    [/Estudia en High School UVB y ten Pase Automático a alguna de nuestras Undergraduate Programs o Ingenierías\./g, 'Study at UVB High School and receive automatic admission to one of our undergraduate or engineering programs.'],
    [/Culturales/g, 'Cultural Activities'],
    [/Cultura Digital I/g, 'Digital Culture I'],
    [/Cultura Digital II\*/g, 'Digital Culture II*'],
    [/Taller de Ciencias I/g, 'Science Workshop I'],
    [/Taller de Ciencias II/g, 'Science Workshop II'],
    [/Gestión de Archivos de Texto/g, 'Text File Management'],
    [/Taller de Cultura Digital/g, 'Digital Culture Workshop'],
    [/Temas Selectos de Matemáticas I/g, 'Selected Topics in Mathematics I'],
    [/Contabilidad I/g, 'Accounting I'],
    [/Derecho I/g, 'Law I'],
    [/Temas Selectos de Matemáticas II/g, 'Selected Topics in Mathematics II'],
    [/Contabilidad II/g, 'Accounting II'],
    [/Derecho II/g, 'Law II'],
    [/Prácticas Profesionales/g, 'Professional Internships'],
    [/Inglés General I/g, 'General English I'],
    [/Inglés General II/g, 'General English II'],
    [/Inglés General III/g, 'General English III'],
    [/Inglés General IV/g, 'General English IV'],
    [/Inglés General V/g, 'General English V'],
    [/Estrategias de Aprendizaje y Habilidades Digitales/g, 'Learning Strategies and Digital Skills'],
    [/Pensamiento crítico/g, 'Critical Thinking'],
    [/Probabilidad y Estadística/g, 'Probability and Statistics'],
    [/Matemáticas Aplicadas/g, 'Applied Mathematics'],
    [/Matemáticas Financieras/g, 'Financial Mathematics'],
    [/Contabilidad Financiera/g, 'Financial Accounting'],
    [/Contabilidad Administrativa/g, 'Managerial Accounting'],
    [/Contabilidad de Costos/g, 'Cost Accounting'],
    [/Microeconomía/g, 'Microeconomics'],
    [/Macroeconomía/g, 'Macroeconomics'],
    [/Mercadotecnia/g, 'Marketing'],
    [/Metodología de la Investigación/g, 'Research Methodology'],
    [/Derecho Mercantil/g, 'Commercial Law'],
    [/Derecho Laboral/g, 'Labor Law'],
    [/Comercio Electrónico/g, 'E-Commerce'],
    [/Fotografía Digital/g, 'Digital Photography'],
    [/Manipulación Digital/g, 'Digital Manipulation'],
    [/Programación en Ambiente Web/g, 'Web Environment Programming'],
    [/Control de Calidad/g, 'Quality Control'],
    [/Gestión de la Calidad/g, 'Quality Management'],
    [/Administración Contemporánea/g, 'Contemporary Administration'],
    [/Tecnologías para la Gestión/g, 'Technologies for Management'],
    [/Fundamentos de la Ciencia de Datos/g, 'Foundations of Data Science'],
    [/Narrativa con Datos/g, 'Data Storytelling'],
    [/Diseño y Validación de Instrumentos/g, 'Instrument Design and Validation'],
    [/¡INICIA TU PROCESO DE ADMISIÓN!/g, 'START YOUR ADMISSION PROCESS!'],
    [/Realiza tu proceso de incorporación con ayuda de uno de nuestros asesores\./g, 'Complete your enrollment process with the help of one of our advisors.'],
    [/ADMISIONES/g, 'ADMISSIONS'],
    [/Ubicación/g, 'Location'],
    [/Licenciatura en Administración de Negocios Internacionales/g, 'B.A. in International Business Administration'],
    [/Ética en el actuar/g, 'Ethics in Practice'],
    [/Herramientas para la Gestión Internacional/g, 'Tools for International Management'],
    [/Derecho Aduanero/g, 'Customs Law'],
    [/Logística y [Cc]omercio [Ii]nternacional/g, 'Logistics and International Trade'],
    [/Logistics y [Cc]omercio [Ii]nternacional/g, 'Logistics and International Trade'],
    [/Tratados de [Cc]omercio [Ii]nternacional/g, 'International Trade Treaties'],
    [/Seminario de Negocios Internacionales/g, 'International Business Seminar'],
    [/Licenciatura en Contaduría Pública y Finanzas/g, 'B.A. in Public Accounting and Finance'],
    [/Contabilidad de Activos y Pasivos/g, 'Accounting for Assets and Liabilities'],
    [/Prácticas de Auditoría/g, 'Auditing Practice'],
    [/Licenciatura en Comunicación y Medios Digitales/g, 'B.A. in Communication and Digital Media'],
    [/Taller de Redacción/g, 'Writing Workshop'],
    [/Taller de Creatividad Digital/g, 'Digital Creativity Workshop'],
    [/Cultura y Sociedad Digital/g, 'Digital Culture and Society'],
    [/Elementos de la tecnología de la información y comunicación \(TIC\)/g, 'Elements of information and communication technology (ICT)'],
    [/Fundamentos de los procesos sociales en el ámbito social, económico y político/g, 'Foundations of social processes in the social, economic, and political spheres'],
    [/Procesos históricos de México y el mundo/g, 'Historical processes of Mexico and the world'],
    [/Producir textos con base en las reglas gramaticales y ortográficas/g, 'Produce texts based on grammatical and spelling rules'],
    [/Argumentar puntos de vista en público de forma precisa/g, 'Present points of view clearly in public'],
    [/Valorar y describir los procesos del arte, literatura y medios de comunicación/g, 'Assess and describe processes in art, literature, and media'],
    [/Adaptabilidad y apertura a los cambios constantes y a los contextos sociales y políticos/g, 'Adaptability and openness to constant change and social and political contexts'],
    [/Disposición hacia una formación innovadora de vanguardia/g, 'Willingness toward innovative, cutting-edge education'],
    [/Modelos Teóricos de Comunicación/g, 'Theoretical Models of Communication'],
    [/Empatía para Resolver/g, 'Empathy for Problem Solving'],
    [/Análisis y Diseño de Contenidos/g, 'Content Analysis and Design'],
    [/Medios y Legislación/g, 'Media and Legislation'],
    [/Licenciatura en Comercio y Logística Internacional/g, 'B.A. in International Trade and Logistics'],
    [/Licenciatura en Comercio y Logistics Internacional/g, 'B.A. in International Trade and Logistics'],
    [/Bases Jurídicas del Comercio Internacional/g, 'Legal Foundations of International Trade'],
    [/Gestión de Negocios Comerciales y Logísticos/g, 'Commercial and Logistics Business Management'],
    [/Auditoría de la Seguridad en la Cadena de Suministro de Comercio Exterior/g, 'Foreign Trade Supply Chain Security Auditing'],
    [/Geoeconomía Aplicada al Comercio Internacional/g, 'Geoeconomics Applied to International Trade'],
    [/Clasificación Arancelaria de Mercancías de Comercio Exterior/g, 'Tariff Classification of Foreign Trade Goods'],
    [/Cultura de Internacionalización de las Empresas/g, 'Business Internationalization Culture'],
    [/Licenciatura en Cirujano Dentista/g, 'Dental Surgery Program'],
    [/Atención humana y profesional al paciente/g, 'Human and Professional Patient Care'],
    [/Seminario de Casos Clínicos/g, 'Clinical Case Seminar'],
    [/Seminario de Fortalecimiento al Egreso/g, 'Graduation Readiness Seminar'],
    [/Desafíos/g, 'Challenges'],
    [/Realización de tratamientos dentales efectivos/g, 'Ability to perform effective dental treatments'],
    [/Empatía y respeto a la vida/g, 'Empathy and respect for life'],
    [/Actitud positiva de atención al paciente/g, 'Positive patient-care attitude'],
    [/Organización/g, 'Organization'],
    [/Conciencia ética y moral médica/g, 'Medical ethical and moral awareness'],
    [/Mostrar pensamiento crítico y de interés por la atención de la salud de un paciente/g, 'Demonstrate critical thinking and interest in patient health care'],
    [/Morfología General/g, 'General Morphology'],
    [/Microbiología e Inmunología/g, 'Microbiology and Immunology'],
    [/Procesos Biológicos/g, 'Biological Processes'],
    [/Introducción a la Práctica Odontológica/g, 'Introduction to Dental Practice'],
    [/Introducción a la Odontología/g, 'Introduction to Dentistry'],
    [/Fisiología General/g, 'General Physiology'],
    [/Morfología de Cabeza y Cuello/g, 'Head and Neck Morphology'],
    [/Morfofisiología Dental/g, 'Dental Morphophysiology'],
    [/Odontología Preventiva/g, 'Preventive Dentistry'],
    [/Licenciatura en Diseño y Comunicación Gráfica/g, 'B.A. in Design and Graphic Communication'],
    [/Desarrollo web y de apps/g, 'Web and App Development'],
    [/Metodología del Diseño y Gestión de Proyectos Creativos/g, 'Design Methodology and Creative Project Management'],
    [/Conocimientos del área de ciencias básicas/g, 'Knowledge in the basic sciences area'],
    [/Tecnología/g, 'Technology'],
    [/Principios de matemáticas/g, 'Principles of mathematics'],
    [/Bases de metodología de la investigación/g, 'Foundations of research methodology'],
    [/Bases de inglés/g, 'English foundations'],
    [/Síntesis visual/g, 'Visual synthesis'],
    [/Conocimientos básicos en arte/g, 'Basic knowledge of art'],
    [/Disposición para trabajar bajo presión/g, 'Willingness to work under pressure'],
    [/Fundamentos del Diseño/g, 'Foundations of Design'],
    [/Iniciación al Dibujo/g, 'Introduction to Drawing'],
    [/Teoría de la Imagen/g, 'Theory of Image'],
    [/Teoría y Manejo del Color/g, 'Color Theory and Management'],
    [/Geometría del Diseño/g, 'Design Geometry'],
    [/Dibujo Anatómico/g, 'Anatomical Drawing'],
    [/Licenciatura en Fisioterapia/g, 'B.A. in Physical Therapy'],
    [/Desarrollo Humano y Social/g, 'Human and Social Development'],
    [/Introducción a la Fisioterapia/g, 'Introduction to Physical Therapy'],
    [/Desarrollo Psicomotor/g, 'Psychomotor Development'],
    [/Gestión en Salud/g, 'Health Management'],
    [/Fisioterapia Neurológica I/g, 'Neurological Physical Therapy I'],
    [/Fisioterapia Cardiopulmonar/g, 'Cardiopulmonary Physical Therapy'],
    [/Fisioterapia Ortopédica y Traumatológica/g, 'Orthopedic and Traumatological Physical Therapy'],
    [/Fisioterapia Neurológica II/g, 'Neurological Physical Therapy II'],
    [/Fisioterapia Dermato Funcional/g, 'Dermatofunctional Physical Therapy'],
    [/Fisioterapia Urogineco Obstétrica/g, 'Urogynecological and Obstetric Physical Therapy'],
    [/Fisioterapia Comunitaria/g, 'Community Physical Therapy'],
    [/Fisioterapia Reumatológica/g, 'Rheumatological Physical Therapy'],
    [/Fisioterapia en Actividad Física y Deporte/g, 'Physical Therapy in Physical Activity and Sports'],
    [/Fisioterapia Geriátrica/g, 'Geriatric Physical Therapy'],
    [/Seminario Integrador en Fisioterapia I/g, 'Integrative Seminar in Physical Therapy I'],
    [/Estancia de Práctica Profesional Hospitalaria en Fisioterapia/g, 'Hospital Professional Practice Residency in Physical Therapy'],
    [/Estancia de Práctica Profesional en Fisioterapia/g, 'Professional Practice Residency in Physical Therapy'],
    [/Seminario Integrador en Fisioterapia II/g, 'Integrative Seminar in Physical Therapy II'],
    [/Movimiento, desarrollo y funcionalidad del cuerpo humano/g, 'Movement, development, and functionality of the human body'],
    [/Prevención, recuperación y rehabilitación de la salud física/g, 'Prevention, recovery, and rehabilitation of physical health'],
    [/Vocación por ayudar, acompañar y mejorar la calidad de vida de las personas/g, 'A vocation for helping, supporting, and improving people\'s quality of life'],
    [/Capacidad de expresión oral, empatía y comunicación efectiva con pacientes/g, 'Oral expression, empathy, and effective communication with patients'],
    [/Habilidad para la observación clínica y evaluación física/g, 'Skill in clinical observation and physical assessment'],
    [/Pensamiento analítico y razonamiento lógico aplicado a la rehabilitación/g, 'Analytical thinking and logical reasoning applied to rehabilitation'],
    [/Dominio de técnicas y métodos terapéuticos en contextos clínicos/g, 'Mastery of therapeutic techniques and methods in clinical contexts'],
    [/Resolución de problemas mediante enfoques personalizados y evidencia científica/g, 'Problem-solving through personalized approaches and scientific evidence'],
    [/Disposición al aprendizaje continuo y actualización profesional constante/g, 'Willingness toward continuous learning and constant professional updating'],
    [/Trabajo en equipo de forma empática, participativa y colaborativa/g, 'Teamwork in an empathetic, participatory, and collaborative way'],
    [/Interés por el bienestar físico y emocional de las personas/g, 'Interest in people\'s physical and emotional well-being'],
    [/Responsabilidad ética en la atención, trato y acompañamiento al paciente/g, 'Ethical responsibility in patient care, treatment, and support'],
    [/Licenciatura en Medicina/g, 'M.D. Program'],
    [/Desarrollo y función del cuerpo humano/g, 'Development and Function of the Human Body'],
    [/Desarrollo del pensamiento lógico-matemático, abstracto, analítico y crítico/g, 'Development of logical-mathematical, abstract, analytical, and critical thinking'],
    [/Agresión y Defensa en Medicina Humana/g, 'Aggression and Defense in Human Medicine'],
    [/Medicina Comunitaria/g, 'Community Medicine'],
    [/Medicina Familiar/g, 'Family Medicine'],
    [/Medicina Legal y Forense/g, 'Legal and Forensic Medicine'],
    [/Medicina Interna/g, 'Internal Medicine'],
    [/Seminario Integrador I/g, 'Integrative Seminar I'],
    [/Seminario Integrador II/g, 'Integrative Seminar II'],
    [/Internado: Medicina Familiar/g, 'Internship: Family Medicine'],
    [/Internado: Medicina Interna/g, 'Internship: Internal Medicine'],
    [/Investigación como disciplina de aprendizaje constante/g, 'Research as a discipline of continuous learning'],
    [/Vocación por ayudar, servir y contribuir/g, 'A vocation to help, serve, and contribute'],
    [/Capacidad de expresión oral y escrita/g, 'Strong oral and written communication skills'],
    [/Capacidad de observación, selección, análisis, clasificación y síntesis de la información/g, 'Ability to observe, select, analyze, classify, and synthesize information'],
    [/Manejo de métodos de investigación y de trabajo acordes a su contexto formativo/g, 'Use of research and work methods appropriate to the educational context'],
    [/Capacidad para abordar y resolver problemas a partir de métodos establecidos/g, 'Ability to address and solve problems using established methods'],
    [/Aprendizaje independiente, permanente y con alto compromiso para su actualización y formación constantes/g, 'Independent, ongoing learning with a strong commitment to constant updating and professional development'],
    [/Aprendizaje independiente, permanente y con alto compromiso para su actualización/g, 'Independent, ongoing learning with a strong commitment to continuous updating'],
    [/Interés por el ámbito clínico/g, 'Interest in the clinical field'],
    [/Biología Celular/g, 'Cell Biology'],
    [/Estructura y Función Humana/g, 'Human Structure and Function'],
    [/Inglés Científico/g, 'Scientific English'],
    [/Salud Pública/g, 'Public Health'],
    [/Práctica Médica I/g, 'Medical Practice I'],
    [/Ética Profesional/g, 'Professional Ethics'],
    [/Licenciatura en Psicología/g, 'B.A. in Psychology'],
    [/Introducción al Periodismo/g, 'Introduction to Journalism'],
    [/Géneros Periodísticos/g, 'Journalistic Genres'],
    [/Producción Audiovisual/g, 'Audiovisual Production'],
    [/Técnicas de Expresión en Medios/g, 'Media Expression Techniques'],
    [/Producción Literaria/g, 'Literary Production'],
    [/Sociología de la Comunicación/g, 'Sociology of Communication'],
    [/Técnicas de Animación Digital/g, 'Digital Animation Techniques'],
    [/Diseñar para Compartir/g, 'Design for Sharing'],
    [/Investigación Cuantitativa de Mercados/g, 'Quantitative Market Research'],
    [/Diseño Digital Aplicado a la Web/g, 'Digital Design Applied to the Web'],
    [/Investigación Cualitativa de Mercados/g, 'Qualitative Market Research'],
    [/Comunicación Política/g, 'Political Communication'],
    [/Comunicación Organizacional/g, 'Organizational Communication'],
    [/Campañas y Plan de Medios/g, 'Campaigns and Media Planning'],
    [/Producción de Cine/g, 'Film Production'],
    [/Medición de Impactos en Medios Digitales/g, 'Impact Measurement in Digital Media'],
    [/Problemas y Estrategias de Comunicación/g, 'Communication Problems and Strategies'],
    [/Vocería y Comunicación Digital/g, 'Spokespersonship and Digital Communication'],
    [/Proyectos de Comunicación Transmedia/g, 'Transmedia Communication Projects'],
    [/Trabajo en equipo multidisciplinario en entornos de salud/g, 'Multidisciplinary teamwork in health environments'],
    [/Agresión y Defensa/g, 'Aggression and Defense'],
    [/Nutrición y Metabolismo/g, 'Nutrition and Metabolism'],
    [/Evaluación y Diagnóstico I/g, 'Evaluation and Diagnosis I'],
    [/Bioética y Profesionalismo/g, 'Bioethics and Professionalism'],
    [/Biomecánica/g, 'Biomechanics'],
    [/Ejercicio Terapéutico/g, 'Therapeutic Exercise'],
    [/Interacción Clínico Patológico/g, 'Clinical-Pathological Interaction'],
    [/Fisiología del Ejercicio/g, 'Exercise Physiology'],
    [/Evaluación Funcional/g, 'Functional Assessment'],
    [/Formates Terapéuticas Manuales/g, 'Manual Therapeutic Techniques'],
    [/Evaluación y Diagnóstico II/g, 'Evaluation and Diagnosis II'],
    [/Formates Terapéuticas/g, 'Therapeutic Techniques'],
    [/Epidemiología y Bioestadística/g, 'Epidemiology and Biostatistics'],
    [/Interacción Clínico Farmacológico/g, 'Clinical-Pharmacological Interaction'],
    [/Liderazgo y Negociación/g, 'Leadership and Negotiation'],
    [/Semiótica y Comunicación Visual/g, 'Semiotics and Visual Communication'],
    [/Diseño de Imágenes Vectoriales/g, 'Vector Image Design'],
    [/Sistemas de Impresión/g, 'Printing Systems'],
    [/Diseño de Ediciones Digitales/g, 'Digital Publishing Design'],
    [/Diseño Tipográfico/g, 'Typographic Design'],
    [/Diseño y Arte Digital/g, 'Design and Digital Art'],
    [/Ilustración Digital/g, 'Digital Illustration'],
    [/Producción Fotográfica/g, 'Photographic Production'],
    [/Historia del Diseño/g, 'History of Design'],
    [/Diseño Publicitario/g, 'Advertising Design'],
    [/Señalética y Señalización/g, 'Signage and Wayfinding'],
    [/Diseño Gráfico y Soportes Tridimensionales/g, 'Graphic Design and Three-Dimensional Media'],
    [/Modelado y Animación 3D/g, '3D Modeling and Animation'],
    [/Diseño y Edición Digital de Video/g, 'Digital Video Design and Editing'],
    [/Diseño Aplicado al Envase/g, 'Packaging Design'],
    [/Diseño Web/g, 'Web Design'],
    [/Diseño para Social Media/g, 'Design for Social Media'],
    [/Diseño y Comunicación de Marca/g, 'Brand Design and Communication'],
    [/Legislación para el Diseño/g, 'Design Legislation'],
    [/Patología General/g, 'General Pathology'],
    [/Farmacología/g, 'Pharmacology'],
    [/Bases de la Nutrición/g, 'Foundations of Nutrition'],
    [/Introducción a la Operatoria Dental/g, 'Introduction to Dental Operative Practice'],
    [/Radiología e Imagenología/g, 'Radiology and Imaging'],
    [/Patología Bucal/g, 'Oral Pathology'],
    [/Emergencias Médicas/g, 'Medical Emergencies'],
    [/Semiología y Diagnóstico/g, 'Semiology and Diagnosis'],
    [/Procesos de Operatoria Odontológica/g, 'Dental Operative Processes'],
    [/Técnicas Quirúrgicas/g, 'Surgical Techniques'],
    [/Prótesis/g, 'Prosthodontics'],
    [/Odontología Restauradora/g, 'Restorative Dentistry'],
    [/Oclusión/g, 'Occlusion'],
    [/Public Health en Odontología/g, 'Public Health in Dentistry'],
    [/Clínica de Endodoncia/g, 'Endodontics Clinic'],
    [/Clínica de Periodoncia/g, 'Periodontics Clinic'],
    [/Clínica Protésica/g, 'Prosthodontics Clinic'],
    [/Odontología Restauradora, Estética e Integral/g, 'Restorative, Esthetic, and Comprehensive Dentistry'],
    [/Clínica Integral I/g, 'Comprehensive Clinic I'],
    [/Odontología Infantil/g, 'Pediatric Dentistry'],
    [/Clínica Integral II/g, 'Comprehensive Clinic II'],
    [/Clínica de Odontología Infantil/g, 'Pediatric Dentistry Clinic'],
    [/Restorative Dentistry, Estética e Integral/g, 'Restorative, Esthetic, and Comprehensive Dentistry'],
    [/Clínica de Pediatric Dentistry/g, 'Pediatric Dentistry Clinic'],
    [/Odontología Geriátrica/g, 'Geriatric Dentistry'],
    [/Cirugía Oral y Maxilofacial/g, 'Oral and Maxillofacial Surgery'],
    [/Clínica Integral III/g, 'Comprehensive Clinic III'],
    [/Odontología Legal y Forense/g, 'Legal and Forensic Dentistry'],
    [/Implantología/g, 'Implantology'],
    [/Preservar y restaurar la salud/g, 'Preserve and restore health'],
    [/Sistema Hematopoyético/g, 'Hematopoietic System'],
    [/Biología Molecular y Genética/g, 'Molecular Biology and Genetics'],
    [/Fisiopatología I/g, 'Pathophysiology I'],
    [/Inglés Técnico Médico/g, 'Medical Technical English'],
    [/Biotecnología e Informática/g, 'Biotechnology and Informatics'],
    [/Clínica Integrada/g, 'Integrated Clinic'],
    [/Fisiopatología II/g, 'Pathophysiology II'],
    [/Pediatría/g, 'Pediatrics'],
    [/Fisiopatología III/g, 'Pathophysiology III'],
    [/Administración y Economía de la Salud/g, 'Health Administration and Economics'],
    [/Epidemiología/g, 'Epidemiology'],
    [/Ginecología y Obstetricia/g, 'Gynecology and Obstetrics'],
    [/Inglés de la Práctica Clínica/g, 'English for Clinical Practice'],
    [/Electiva Médica I/g, 'Medical Elective I'],
    [/Electiva Médica II/g, 'Medical Elective II'],
    [/Gerontología/g, 'Gerontology'],
    [/Internado: Ginecología y Obstetricia/g, 'Internship: Gynecology and Obstetrics'],
    [/Internado: Cirugía General/g, 'Internship: General Surgery'],
    [/Internado: Pediatría Clínica/g, 'Internship: Clinical Pediatrics'],
    [/Internado: Pediatrics Clínica/g, 'Internship: Clinical Pediatrics'],
    [/Economía y finanzas internacionales/g, 'International economics and finance'],
    [/Promoción de exportaciones/g, 'Export promotion'],
    [/Legislación aduanal/g, 'Customs legislation'],
    [/Evaluación de proyectos/g, 'Project evaluation'],
    [/Negociación intercultural/g, 'Intercultural negotiation'],
    [/Análisis de mercados financieros/g, 'Financial market analysis'],
    [/Uso de tecnologías aplicadas a los negocios/g, 'Use of technologies applied to business'],
    [/Resolución de problemas/g, 'Problem solving'],
    [/Economía y Finanzas Internacionales/g, 'International Economics and Finance'],
    [/Bases metodológicas de la Investigación/g, 'Methodological Foundations of Research'],
    [/Negociación Intercultural/g, 'Intercultural Negotiation'],
    [/Análisis de Mercados Financieros/g, 'Financial Market Analysis'],
    [/Operación Aduanera Empresarial/g, 'Business Customs Operations'],
    [/Legislación Aduanal/g, 'Customs Legislation'],
    [/Formulación y Evaluación de Proyectos de Internacionalización/g, 'Design and Evaluation of Internationalization Projects'],
    [/Promoción de Exportaciones/g, 'Export Promotion'],
    [/Contexto económico, político y social del país/g, 'Economic, political, and social context of the country'],
    [/Interés por el fenómeno de la globalización/g, 'Interest in the phenomenon of globalization'],
    [/Interés por el emprendimiento y desarrollo de negocios/g, 'Interest in entrepreneurship and business development'],
    [/Visión de internacionalidad en los procesos de negocio/g, 'An international outlook in business processes'],
    [/Conocimientos básicos de geografía política y de un tercer idioma/g, 'Basic knowledge of political geography and a third language'],
    [/Habilidad de negociación/g, 'Negotiation skills'],
    [/Toma de decisiones rápida y asertiva/g, 'Quick and assertive decision-making'],
    [/Comunicación clara y concisa en diferentes idiomas/g, 'Clear and concise communication in different languages'],
    [/Trabajo bajo presión/g, 'Ability to work under pressure'],
    [/Visión de proyección internacional/g, 'International projection mindset'],
    [/Empático/g, 'Empathetic'],
    [/Abastecimiento y Distribución/g, 'Supply and Distribution'],
    [/Tráfico y Transporte Internacional/g, 'International Traffic and Transportation'],
    [/Trámites Aduanales/g, 'Customs Procedures'],
    [/Administración de la Cadena de Suministro/g, 'Supply Chain Management'],
    [/Distribución Internacional/g, 'International Distribution'],
    [/Sistemas de Clasificación Arancelaria/g, 'Tariff Classification Systems'],
    [/Procesos básicos contables/g, 'Basic accounting processes'],
    [/Contexto económico del país/g, 'Economic context of the country'],
    [/Razonamiento lógico-matemático/g, 'Logical-mathematical reasoning'],
    [/Negociación/g, 'Negotiation'],
    [/Honesto con el manejo de recursos e información confidencial/g, 'Honest in handling resources and confidential information'],
    [/Preocupado por el desarrollo y proyección económica internacional del país/g, 'Concerned with the country\'s international economic development and projection'],
    [/Contribuciones de Personas Físicas y Morales/g, 'Taxes for Individuals and Corporations'],
    [/Administración Financiera/g, 'Financial Management'],
    [/Fundamentos de Auditoría/g, 'Foundations of Auditing'],
    [/Dictámenes Especiales/g, 'Special Reports'],
    [/Formulación y Evaluación de Proyectos de Inversión/g, 'Design and Evaluation of Investment Projects'],
    [/Finanzas Bursátiles/g, 'Stock Market Finance'],
    [/Pronósticos Financieros/g, 'Financial Forecasting'],
    [/Procesos Contables en un Sistema Electrónico/g, 'Accounting Processes in an Electronic System'],
    [/Laredo 1107, Col\. La Laguna/g, '1107 Laredo, La Laguna District'],
    [/Ciclo /g, 'Term '],
  ];

  for (const [pattern, replacement] of replacements) {
    out = out.replace(pattern, replacement);
  }

  out = localizeInternalHrefs(out, '/en');
  out = out.replace(/<html lang="[^"]+"/g, '<html lang="en"');

  return injectLanguageSwitch(out, true);
}
